project_id = "zfsqubtipuzpibynrufa"

[functions.verify-payment]
verify_jwt = false

[functions.seller-api]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = false

[functions.admin-add-seller]
verify_jwt = false
